name: Metrics

on:
  schedule:
    - cron: "22 0 * * *"
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: show.svg
          token: ${{ secrets.GH_TOKEN }}

          plugin_languages: yes
          plugin_languages_indepth: yes
        #   plugin_languages_threshold: 1%
          plugin_languages_details: percentage

          # plugin_activity: True
          # plugin_activity_visibility: public
          # plugin_activity_filter: issue,pr,release,fork
          # plugin_activity_limit: 10

